name: snapstore
version: 0.2
confinement: strict
grade: devel
summary: Minimalist snap store
description: ...

apps:
  snapstore:
    command: snapstore
    daemon: simple
    plugs: [network, network-bind]

parts:
  # Setup the python3 environment and grab the dependencies
  prerequisites:
    source: .
    plugin: python
    python-version: python3
    python-packages:
      - setuptools